name: tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php:
          - 8.4

    name: PHP:${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, inotify
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache"

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Start Chrome Driver
        run: |
          vendor/bin/dusk-updater detect --no-interaction
          vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          PHP_CLI_SERVER_WORKERS: 6

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*
