name: tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11.*, 12.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 11.*
            testbench-dusk: 9.*
          - laravel: 12.*
            testbench-dusk: 10.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, inotify
          coverage: none

      - name: Installed dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench-dusk:${{ matrix.testbench-dusk }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Update Chrome
        run: vendor/bin/dusk-updater detect --no-interaction

      - name: Execute tests
        run: |
          mkdir -p vendor/orchestra/testbench-dusk/laravel/bootstrap/cache
          chmod -R 777 vendor/orchestra/testbench-dusk/laravel/bootstrap/cache
          vendor/bin/phpunit
        env:
          PHP_CLI_SERVER_WORKERS: 4

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*
