name: tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.4]
        laravel: [12.*]
        include:
          - laravel: 12.*
            dependencies: "laravel/framework:12.*"

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, inotify
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache"

      - name: Show Composer Versions
        run: composer show -D

      - name: Execute Unit tests
        run: vendor/bin/phpunit tests/Unit
        env:
          PHP_CLI_SERVER_WORKERS: 4

      - name: Update Chrome
        run: vendor/bin/dusk-updater detect --no-interaction

      - name: Execute Browser tests (Attempt 1)
        id: dusk_attempt_1
        run: vendor/bin/phpunit tests/Browser
        continue-on-error: true
        env:
          PHP_CLI_SERVER_WORKERS: 4

      - name: Execute Browser tests (Attempt 2)
        id: dusk_attempt_2
        if: steps.dusk_attempt_1.outcome == 'failure'
        run: vendor/bin/phpunit tests/Browser
        env:
          PHP_CLI_SERVER_WORKERS: 4

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*
